server:
  port: 8701

spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka
zuul:
  routes:
    api:
      account:
        path: /api/account/**
        serviceId: store-account

